version: '3.7'
services:

  php-fpm:
    image: localhost/boxes-fpm:latest
    container_name: boxes-fpm
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=${XDEBUG_PORT}
    ports:
      - "${XDEBUG_PORT}:9001"
  
  nginx:
    image: localhost/boxes-nginx:latest
    restart: always
    container_name: boxes-nginx
    ports:
      - ${APP_WEB_PORT}:80
    depends_on:
      - php-fpm
    volumes:
      - ./web:/var/www/html/web
    environment:
      PHP_UPSTREAM_CONTAINER: php-fpm
      PHP_UPSTREAM_PORT: 9000
      APP_WEB_PORT: ${APP_WEB_PORT}

